### PR TITLE
Task/341 update board definitions

### PR DESCRIPTION
**Pull request by amirna2**
**Describe at a high level the solution you're providing**
This PR addresses issue #341
The board definition header files were updated to the most commonly used boards on CDP project.
This also simplified how they are included in `cdpcfg.h`

Additionally, a single global header file `CDP.h` was created to make it easier to include in Arduino sketches.

Finally, optimized dependencies to include only what CDP and the examples need.

**Is this related to an open issue?**
#341

**Testing Methodology. How can someone test your pull request?** 
- Run Unit tests on Heltec Lora V3, LILYGO T_Beam (sx1262) and CubeCell Board v2
- Uploaded basic duck examples  (DuckLink, MamaDuck and PapaDuck-Basic) on all 3 boards above.

### CODE REVIEW

**Comment by amirna2** [comment]
Spent some time chasing why the Heltec v3 was failing under CI
Turns out Arduino CLI apparently doesn't get the same Arduino board definition as Arduino IDE.
We have 3 build systems and 3 board directives.

```
// This is becoming ridiculous. 3 different build systems, 3 different ways to define the board name.
// Arduino IDE: ARDUINO_WIFI_LORA_32_V3
// PlatformIO: ARDUINO_heltec_wifi_lora_32_V3
// Arduino Cli: ARDUINO_heltec_wifi_32_lora_V3
#if defined(ARDUINO_WIFI_LORA_32_V3) || defined(ARDUINO_heltec_wifi_lora_32_V3) || defined(ARDUINO_heltec_wifi_32_lora_V3)
#define CDP_BOARD_NAME "Heltec WiFi LoRa 32 V3"
#define CDPCFG_RADIO_SX1262
```

**Comment by amirna2** [comment]
Added TTGO_LORA_32_V1 support for CDP and basic examples.

**Comment by amirna2** [comment]
Are we okay with this? I think this should be merged first into the 4.0 branch. But I need some confirmation that the CDP library is building successfully on other people's machine.

**Review by hawk4031 — APPROVED** [review]
This looks great! Very excited to see these changes merged.

**Comment by tqrahman** [comment]
I did a standard network test and can confirm that the PapaDuck received messages from two MamaDucks and it should a hop.

**Pull request merged**
