### PR TITLE
refactor: #423 replace arduino string with std::string

### LINKED ISSUE #423: Replace Arduino String with std::String
**Describe the bug**
The current examples have some traces of `String` which is Arduino. It should be replaced with `std:string`

**Screenshots**
Screenshot 2024-04-16 at 12 30 06 AM

### PR DESCRIPTION
**Pull request by miguelcsx**
- the current examples contained traces of arduino string class

- replaced with std::string to align with standards

**What is is PR for?**

- [x] Code update
- [ ] Documentation update
- [ ] Infrastructure update

**What does this PR do?**  
This PR refactors the example code by replacing the Arduino-specific String class with the standard C++ std::string. The change ensures the code is more portable and aligns with common C++ practices.

**Is this related to an open issue?**  

- closes #423 

**Testing methodology**  
Code was compiled and tested to ensure functionality is not impacted by the change.

**Additional context**  
- Replaced instances of String with std::string across all example files.

**Checklist**
Before you submit this pull request, please make sure you have done the following:

_General_  

- [x] Contribution Guidelines: Have you read the contribution guidelines?
- [x] Code of Conduct: Have you read the code of conduct?
- [x] Documentation: If applicable, have you added or updated all relevant documentation?

_For Code Updates_  

- [ ] Hardware Validation: If relevant, have you validated your changes on actual supported Duck hardware?
- [ ] Unit Tests: Have you run the unit tests on the device?
- [ ] Network Testing: If applicable, have you tested your changes on a Duck network?
- [ ] Licensing: Have you added a copyright and license header to each new file?

_Tested Targets (Please check all that apply)_

- [ ] All
- [ ] Heltec LoRa v3
- [ ] Heltec LoRa v2
- [ ] Heltec CubeCell Series
- [ ] TTGO T-Beam (SX1262)
- [ ] Others

### CODE REVIEW

**Comment by miguelcsx** [comment]
@faradaym I already did the rabase, and the checks have already passed, I also joined the discord, thanks :+1:

**Comment by faradaym** [comment]
I have added a review line showing how to fix one type error. There are several more in the Basic-Duck/PapaDuck.ino and some in the other example files. If you need help setting up the environment to check the code, you can reference our [wiki here](https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/wiki/platformio) -- you shouldn't need a board to be able to fix this, just getting it to pass a compilation check should be good!

**Comment by miguelcsx** [comment]
@faradaym I followed your instructions, and all the checks passed correctly, thanks :+1:

**Review by faradaym — APPROVED** [review]

**Comment by tqrahman** [comment]
The PapaDuck example is not compiling after converting the `String convertToHex(byte* data, int size);` to `std::string convertToHex(byte* data, int size);`. I am getting this error: 

Screenshot 2024-10-28 at 1 17 08 PM

**Pull request merged**
